version: '3'
services:
  database:
    image: "postgres:13"
    # command: ["postgres", "-c", "log_statement=all"]
    # env_file:
    #   - database.env
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker

    volumes:
      - ./sql_scripts/startup_sql_scripts:/docker-entrypoint-initdb.d/
    ports: 
      - 5432:5432
  
  loader:
    depends_on: 
      - database 
    build: 
      dockerfile: "loader.Dockerfile"
      context: .
    environment: 
      - POSTGRES_PASSWORD=docker
      - DATA_DATE=2021-04-29
    volumes: 
      - ./data/:/data/
      - ./sql_scripts/:/sql_scripts/
    links:
      - database
    command: ["./wait-for-postgres.sh", "database", "python", "musicdwh.py"]


  # busybox:
  #   depends_on: 
  #     - database     
  #   image: busybox
  #   command: tail -F anything
  #   links:
  #     - database
    # entrypoint: "ping -c5 database && nc -vc database 5432"
